//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCliente.NavalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Objetos")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool conectadoField;
        
        private string mailField;
        
        private AppCliente.NavalService.ListaDOfJuego209EgP0h mis_partidasField;
        
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool conectado {
            get {
                return this.conectadoField;
            }
            set {
                if ((this.conectadoField.Equals(value) != true)) {
                    this.conectadoField = value;
                    this.RaisePropertyChanged("conectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.ListaDOfJuego209EgP0h mis_partidas {
            get {
                return this.mis_partidasField;
            }
            set {
                if ((object.ReferenceEquals(this.mis_partidasField, value) != true)) {
                    this.mis_partidasField = value;
                    this.RaisePropertyChanged("mis_partidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDOfJuego209EgP0h", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Arbol")]
    [System.SerializableAttribute()]
    public partial class ListaDOfJuego209EgP0h : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int countField;
        
        private AppCliente.NavalService.NodeOfJuego209EgP0h finField;
        
        private AppCliente.NavalService.NodeOfJuego209EgP0h raizField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.NodeOfJuego209EgP0h fin {
            get {
                return this.finField;
            }
            set {
                if ((object.ReferenceEquals(this.finField, value) != true)) {
                    this.finField = value;
                    this.RaisePropertyChanged("fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.NodeOfJuego209EgP0h raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeOfJuego209EgP0h", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Nodos")]
    [System.SerializableAttribute()]
    public partial class NodeOfJuego209EgP0h : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AppCliente.NavalService.NodeOfJuego209EgP0h anteriorField;
        
        private AppCliente.NavalService.Juego itemField;
        
        private int keyField;
        
        private string key_Field;
        
        private AppCliente.NavalService.NodeOfJuego209EgP0h siguienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.NodeOfJuego209EgP0h anterior {
            get {
                return this.anteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.anteriorField, value) != true)) {
                    this.anteriorField = value;
                    this.RaisePropertyChanged("anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.Juego item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                if ((this.keyField.Equals(value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key_ {
            get {
                return this.key_Field;
            }
            set {
                if ((object.ReferenceEquals(this.key_Field, value) != true)) {
                    this.key_Field = value;
                    this.RaisePropertyChanged("key_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.NodeOfJuego209EgP0h siguiente {
            get {
                return this.siguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.siguienteField, value) != true)) {
                    this.siguienteField = value;
                    this.RaisePropertyChanged("siguiente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Juego", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Objetos")]
    [System.SerializableAttribute()]
    public partial class Juego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int destruidosField;
        
        private bool ganoField;
        
        private string oponenteField;
        
        private int sobrevivientesField;
        
        private int unidades_desplegadasField;
        
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int destruidos {
            get {
                return this.destruidosField;
            }
            set {
                if ((this.destruidosField.Equals(value) != true)) {
                    this.destruidosField = value;
                    this.RaisePropertyChanged("destruidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool gano {
            get {
                return this.ganoField;
            }
            set {
                if ((this.ganoField.Equals(value) != true)) {
                    this.ganoField = value;
                    this.RaisePropertyChanged("gano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string oponente {
            get {
                return this.oponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.oponenteField, value) != true)) {
                    this.oponenteField = value;
                    this.RaisePropertyChanged("oponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sobrevivientes {
            get {
                return this.sobrevivientesField;
            }
            set {
                if ((this.sobrevivientesField.Equals(value) != true)) {
                    this.sobrevivientesField = value;
                    this.RaisePropertyChanged("sobrevivientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int unidades_desplegadas {
            get {
                return this.unidades_desplegadasField;
            }
            set {
                if ((this.unidades_desplegadasField.Equals(value) != true)) {
                    this.unidades_desplegadasField = value;
                    this.RaisePropertyChanged("unidades_desplegadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nodo", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Nodos")]
    [System.SerializableAttribute()]
    public partial class Nodo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AppCliente.NavalService.Nodo derField;
        
        private AppCliente.NavalService.Persona itemField;
        
        private AppCliente.NavalService.Nodo izqField;
        
        private string keyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.Nodo der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.Persona item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppCliente.NavalService.Nodo izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unidad", Namespace="http://schemas.datacontract.org/2004/07/WSproyecto1.Objetos")]
    [System.SerializableAttribute()]
    public partial class Unidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int alcanceField;
        
        private int alcance_Field;
        
        private int danyoField;
        
        private string duenyoField;
        
        private int hpField;
        
        private int movimientoField;
        
        private string nombreField;
        
        private string tipoField;
        
        private bool visibleField;
        
        private bool vivoField;
        
        private string xField;
        
        private int yField;
        
        private int zField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int alcance {
            get {
                return this.alcanceField;
            }
            set {
                if ((this.alcanceField.Equals(value) != true)) {
                    this.alcanceField = value;
                    this.RaisePropertyChanged("alcance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int alcance_ {
            get {
                return this.alcance_Field;
            }
            set {
                if ((this.alcance_Field.Equals(value) != true)) {
                    this.alcance_Field = value;
                    this.RaisePropertyChanged("alcance_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int danyo {
            get {
                return this.danyoField;
            }
            set {
                if ((this.danyoField.Equals(value) != true)) {
                    this.danyoField = value;
                    this.RaisePropertyChanged("danyo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string duenyo {
            get {
                return this.duenyoField;
            }
            set {
                if ((object.ReferenceEquals(this.duenyoField, value) != true)) {
                    this.duenyoField = value;
                    this.RaisePropertyChanged("duenyo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int hp {
            get {
                return this.hpField;
            }
            set {
                if ((this.hpField.Equals(value) != true)) {
                    this.hpField = value;
                    this.RaisePropertyChanged("hp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int movimiento {
            get {
                return this.movimientoField;
            }
            set {
                if ((this.movimientoField.Equals(value) != true)) {
                    this.movimientoField = value;
                    this.RaisePropertyChanged("movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                if ((this.visibleField.Equals(value) != true)) {
                    this.visibleField = value;
                    this.RaisePropertyChanged("visible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool vivo {
            get {
                return this.vivoField;
            }
            set {
                if ((this.vivoField.Equals(value) != true)) {
                    this.vivoField = value;
                    this.RaisePropertyChanged("vivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string x {
            get {
                return this.xField;
            }
            set {
                if ((object.ReferenceEquals(this.xField, value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int z {
            get {
                return this.zField;
            }
            set {
                if ((this.zField.Equals(value) != true)) {
                    this.zField = value;
                    this.RaisePropertyChanged("z");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NavalService.INavalWarsService")]
    public interface INavalWarsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newPersona", ReplyAction="http://tempuri.org/INavalWarsService/newPersonaResponse")]
        AppCliente.NavalService.Persona newPersona(string password, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newPersona", ReplyAction="http://tempuri.org/INavalWarsService/newPersonaResponse")]
        System.Threading.Tasks.Task<AppCliente.NavalService.Persona> newPersonaAsync(string password, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/insertar", ReplyAction="http://tempuri.org/INavalWarsService/insertarResponse")]
        bool insertar(string nick, AppCliente.NavalService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/insertar", ReplyAction="http://tempuri.org/INavalWarsService/insertarResponse")]
        System.Threading.Tasks.Task<bool> insertarAsync(string nick, AppCliente.NavalService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/buscar", ReplyAction="http://tempuri.org/INavalWarsService/buscarResponse")]
        AppCliente.NavalService.Nodo buscar(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/buscar", ReplyAction="http://tempuri.org/INavalWarsService/buscarResponse")]
        System.Threading.Tasks.Task<AppCliente.NavalService.Nodo> buscarAsync(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/logIn", ReplyAction="http://tempuri.org/INavalWarsService/logInResponse")]
        AppCliente.NavalService.Nodo logIn(string nick, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/logIn", ReplyAction="http://tempuri.org/INavalWarsService/logInResponse")]
        System.Threading.Tasks.Task<AppCliente.NavalService.Nodo> logInAsync(string nick, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/eliminar", ReplyAction="http://tempuri.org/INavalWarsService/eliminarResponse")]
        bool eliminar(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/eliminar", ReplyAction="http://tempuri.org/INavalWarsService/eliminarResponse")]
        System.Threading.Tasks.Task<bool> eliminarAsync(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/modificar", ReplyAction="http://tempuri.org/INavalWarsService/modificarResponse")]
        bool modificar(string nick, AppCliente.NavalService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/modificar", ReplyAction="http://tempuri.org/INavalWarsService/modificarResponse")]
        System.Threading.Tasks.Task<bool> modificarAsync(string nick, AppCliente.NavalService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cleanBinario", ReplyAction="http://tempuri.org/INavalWarsService/cleanBinarioResponse")]
        void cleanBinario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cleanBinario", ReplyAction="http://tempuri.org/INavalWarsService/cleanBinarioResponse")]
        System.Threading.Tasks.Task cleanBinarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/alturaBinario", ReplyAction="http://tempuri.org/INavalWarsService/alturaBinarioResponse")]
        int alturaBinario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/alturaBinario", ReplyAction="http://tempuri.org/INavalWarsService/alturaBinarioResponse")]
        System.Threading.Tasks.Task<int> alturaBinarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/hojasBinario", ReplyAction="http://tempuri.org/INavalWarsService/hojasBinarioResponse")]
        int hojasBinario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/hojasBinario", ReplyAction="http://tempuri.org/INavalWarsService/hojasBinarioResponse")]
        System.Threading.Tasks.Task<int> hojasBinarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/ramasBinario", ReplyAction="http://tempuri.org/INavalWarsService/ramasBinarioResponse")]
        int ramasBinario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/ramasBinario", ReplyAction="http://tempuri.org/INavalWarsService/ramasBinarioResponse")]
        System.Threading.Tasks.Task<int> ramasBinarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newJuego", ReplyAction="http://tempuri.org/INavalWarsService/newJuegoResponse")]
        AppCliente.NavalService.Juego newJuego(string usuario, string oponente, int unidades_desplegadas, int sobrevivientes, int destruidos, int gano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newJuego", ReplyAction="http://tempuri.org/INavalWarsService/newJuegoResponse")]
        System.Threading.Tasks.Task<AppCliente.NavalService.Juego> newJuegoAsync(string usuario, string oponente, int unidades_desplegadas, int sobrevivientes, int destruidos, int gano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/agregarJuego", ReplyAction="http://tempuri.org/INavalWarsService/agregarJuegoResponse")]
        bool agregarJuego(AppCliente.NavalService.Juego nuevo, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/agregarJuego", ReplyAction="http://tempuri.org/INavalWarsService/agregarJuegoResponse")]
        System.Threading.Tasks.Task<bool> agregarJuegoAsync(AppCliente.NavalService.Juego nuevo, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarArbolBinario", ReplyAction="http://tempuri.org/INavalWarsService/graficarArbolBinarioResponse")]
        bool graficarArbolBinario(string ruta_destino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarArbolBinario", ReplyAction="http://tempuri.org/INavalWarsService/graficarArbolBinarioResponse")]
        System.Threading.Tasks.Task<bool> graficarArbolBinarioAsync(string ruta_destino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarArbolBinarioEspejo", ReplyAction="http://tempuri.org/INavalWarsService/graficarArbolBinarioEspejoResponse")]
        bool graficarArbolBinarioEspejo(string ruta_destino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarArbolBinarioEspejo", ReplyAction="http://tempuri.org/INavalWarsService/graficarArbolBinarioEspejoResponse")]
        System.Threading.Tasks.Task<bool> graficarArbolBinarioEspejoAsync(string ruta_destino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/debug", ReplyAction="http://tempuri.org/INavalWarsService/debugResponse")]
        string debug();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/debug", ReplyAction="http://tempuri.org/INavalWarsService/debugResponse")]
        System.Threading.Tasks.Task<string> debugAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cargaUsuarios", ReplyAction="http://tempuri.org/INavalWarsService/cargaUsuariosResponse")]
        bool cargaUsuarios(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cargaUsuarios", ReplyAction="http://tempuri.org/INavalWarsService/cargaUsuariosResponse")]
        System.Threading.Tasks.Task<bool> cargaUsuariosAsync(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cargaJuegos", ReplyAction="http://tempuri.org/INavalWarsService/cargaJuegosResponse")]
        bool cargaJuegos(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/cargaJuegos", ReplyAction="http://tempuri.org/INavalWarsService/cargaJuegosResponse")]
        System.Threading.Tasks.Task<bool> cargaJuegosAsync(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/setParametrosJuego", ReplyAction="http://tempuri.org/INavalWarsService/setParametrosJuegoResponse")]
        void setParametrosJuego(int filas, int columnas, int unidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/setParametrosJuego", ReplyAction="http://tempuri.org/INavalWarsService/setParametrosJuegoResponse")]
        System.Threading.Tasks.Task setParametrosJuegoAsync(int filas, int columnas, int unidades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/clearMatriz", ReplyAction="http://tempuri.org/INavalWarsService/clearMatrizResponse")]
        void clearMatriz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/clearMatriz", ReplyAction="http://tempuri.org/INavalWarsService/clearMatrizResponse")]
        System.Threading.Tasks.Task clearMatrizAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoFilas", ReplyAction="http://tempuri.org/INavalWarsService/getNoFilasResponse")]
        int getNoFilas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoFilas", ReplyAction="http://tempuri.org/INavalWarsService/getNoFilasResponse")]
        System.Threading.Tasks.Task<int> getNoFilasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoColumnas", ReplyAction="http://tempuri.org/INavalWarsService/getNoColumnasResponse")]
        int getNoColumnas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoColumnas", ReplyAction="http://tempuri.org/INavalWarsService/getNoColumnasResponse")]
        System.Threading.Tasks.Task<int> getNoColumnasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoUnidades", ReplyAction="http://tempuri.org/INavalWarsService/getNoUnidadesResponse")]
        int getNoUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoUnidades", ReplyAction="http://tempuri.org/INavalWarsService/getNoUnidadesResponse")]
        System.Threading.Tasks.Task<int> getNoUnidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoJugador", ReplyAction="http://tempuri.org/INavalWarsService/getNoJugadorResponse")]
        int getNoJugador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/getNoJugador", ReplyAction="http://tempuri.org/INavalWarsService/getNoJugadorResponse")]
        System.Threading.Tasks.Task<int> getNoJugadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/setNoJugador", ReplyAction="http://tempuri.org/INavalWarsService/setNoJugadorResponse")]
        void setNoJugador(int jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/setNoJugador", ReplyAction="http://tempuri.org/INavalWarsService/setNoJugadorResponse")]
        System.Threading.Tasks.Task setNoJugadorAsync(int jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/insertarUnidad", ReplyAction="http://tempuri.org/INavalWarsService/insertarUnidadResponse")]
        bool insertarUnidad(AppCliente.NavalService.Unidad item, int fila, string columna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/insertarUnidad", ReplyAction="http://tempuri.org/INavalWarsService/insertarUnidadResponse")]
        System.Threading.Tasks.Task<bool> insertarUnidadAsync(AppCliente.NavalService.Unidad item, int fila, string columna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newUnidad", ReplyAction="http://tempuri.org/INavalWarsService/newUnidadResponse")]
        AppCliente.NavalService.Unidad newUnidad(string nombre, string x, int y, string duenyo, int vivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/newUnidad", ReplyAction="http://tempuri.org/INavalWarsService/newUnidadResponse")]
        System.Threading.Tasks.Task<AppCliente.NavalService.Unidad> newUnidadAsync(string nombre, string x, int y, string duenyo, int vivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarTablero", ReplyAction="http://tempuri.org/INavalWarsService/graficarTableroResponse")]
        bool graficarTablero(int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INavalWarsService/graficarTablero", ReplyAction="http://tempuri.org/INavalWarsService/graficarTableroResponse")]
        System.Threading.Tasks.Task<bool> graficarTableroAsync(int nivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INavalWarsServiceChannel : AppCliente.NavalService.INavalWarsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NavalWarsServiceClient : System.ServiceModel.ClientBase<AppCliente.NavalService.INavalWarsService>, AppCliente.NavalService.INavalWarsService {
        
        public NavalWarsServiceClient() {
        }
        
        public NavalWarsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NavalWarsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppCliente.NavalService.Persona newPersona(string password, string mail) {
            return base.Channel.newPersona(password, mail);
        }
        
        public System.Threading.Tasks.Task<AppCliente.NavalService.Persona> newPersonaAsync(string password, string mail) {
            return base.Channel.newPersonaAsync(password, mail);
        }
        
        public bool insertar(string nick, AppCliente.NavalService.Persona persona) {
            return base.Channel.insertar(nick, persona);
        }
        
        public System.Threading.Tasks.Task<bool> insertarAsync(string nick, AppCliente.NavalService.Persona persona) {
            return base.Channel.insertarAsync(nick, persona);
        }
        
        public AppCliente.NavalService.Nodo buscar(string nick) {
            return base.Channel.buscar(nick);
        }
        
        public System.Threading.Tasks.Task<AppCliente.NavalService.Nodo> buscarAsync(string nick) {
            return base.Channel.buscarAsync(nick);
        }
        
        public AppCliente.NavalService.Nodo logIn(string nick, string password) {
            return base.Channel.logIn(nick, password);
        }
        
        public System.Threading.Tasks.Task<AppCliente.NavalService.Nodo> logInAsync(string nick, string password) {
            return base.Channel.logInAsync(nick, password);
        }
        
        public bool eliminar(string nick) {
            return base.Channel.eliminar(nick);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarAsync(string nick) {
            return base.Channel.eliminarAsync(nick);
        }
        
        public bool modificar(string nick, AppCliente.NavalService.Persona persona) {
            return base.Channel.modificar(nick, persona);
        }
        
        public System.Threading.Tasks.Task<bool> modificarAsync(string nick, AppCliente.NavalService.Persona persona) {
            return base.Channel.modificarAsync(nick, persona);
        }
        
        public void cleanBinario() {
            base.Channel.cleanBinario();
        }
        
        public System.Threading.Tasks.Task cleanBinarioAsync() {
            return base.Channel.cleanBinarioAsync();
        }
        
        public int alturaBinario() {
            return base.Channel.alturaBinario();
        }
        
        public System.Threading.Tasks.Task<int> alturaBinarioAsync() {
            return base.Channel.alturaBinarioAsync();
        }
        
        public int hojasBinario() {
            return base.Channel.hojasBinario();
        }
        
        public System.Threading.Tasks.Task<int> hojasBinarioAsync() {
            return base.Channel.hojasBinarioAsync();
        }
        
        public int ramasBinario() {
            return base.Channel.ramasBinario();
        }
        
        public System.Threading.Tasks.Task<int> ramasBinarioAsync() {
            return base.Channel.ramasBinarioAsync();
        }
        
        public AppCliente.NavalService.Juego newJuego(string usuario, string oponente, int unidades_desplegadas, int sobrevivientes, int destruidos, int gano) {
            return base.Channel.newJuego(usuario, oponente, unidades_desplegadas, sobrevivientes, destruidos, gano);
        }
        
        public System.Threading.Tasks.Task<AppCliente.NavalService.Juego> newJuegoAsync(string usuario, string oponente, int unidades_desplegadas, int sobrevivientes, int destruidos, int gano) {
            return base.Channel.newJuegoAsync(usuario, oponente, unidades_desplegadas, sobrevivientes, destruidos, gano);
        }
        
        public bool agregarJuego(AppCliente.NavalService.Juego nuevo, string usuario) {
            return base.Channel.agregarJuego(nuevo, usuario);
        }
        
        public System.Threading.Tasks.Task<bool> agregarJuegoAsync(AppCliente.NavalService.Juego nuevo, string usuario) {
            return base.Channel.agregarJuegoAsync(nuevo, usuario);
        }
        
        public bool graficarArbolBinario(string ruta_destino) {
            return base.Channel.graficarArbolBinario(ruta_destino);
        }
        
        public System.Threading.Tasks.Task<bool> graficarArbolBinarioAsync(string ruta_destino) {
            return base.Channel.graficarArbolBinarioAsync(ruta_destino);
        }
        
        public bool graficarArbolBinarioEspejo(string ruta_destino) {
            return base.Channel.graficarArbolBinarioEspejo(ruta_destino);
        }
        
        public System.Threading.Tasks.Task<bool> graficarArbolBinarioEspejoAsync(string ruta_destino) {
            return base.Channel.graficarArbolBinarioEspejoAsync(ruta_destino);
        }
        
        public string debug() {
            return base.Channel.debug();
        }
        
        public System.Threading.Tasks.Task<string> debugAsync() {
            return base.Channel.debugAsync();
        }
        
        public bool cargaUsuarios(string direccion) {
            return base.Channel.cargaUsuarios(direccion);
        }
        
        public System.Threading.Tasks.Task<bool> cargaUsuariosAsync(string direccion) {
            return base.Channel.cargaUsuariosAsync(direccion);
        }
        
        public bool cargaJuegos(string direccion) {
            return base.Channel.cargaJuegos(direccion);
        }
        
        public System.Threading.Tasks.Task<bool> cargaJuegosAsync(string direccion) {
            return base.Channel.cargaJuegosAsync(direccion);
        }
        
        public void setParametrosJuego(int filas, int columnas, int unidades) {
            base.Channel.setParametrosJuego(filas, columnas, unidades);
        }
        
        public System.Threading.Tasks.Task setParametrosJuegoAsync(int filas, int columnas, int unidades) {
            return base.Channel.setParametrosJuegoAsync(filas, columnas, unidades);
        }
        
        public void clearMatriz() {
            base.Channel.clearMatriz();
        }
        
        public System.Threading.Tasks.Task clearMatrizAsync() {
            return base.Channel.clearMatrizAsync();
        }
        
        public int getNoFilas() {
            return base.Channel.getNoFilas();
        }
        
        public System.Threading.Tasks.Task<int> getNoFilasAsync() {
            return base.Channel.getNoFilasAsync();
        }
        
        public int getNoColumnas() {
            return base.Channel.getNoColumnas();
        }
        
        public System.Threading.Tasks.Task<int> getNoColumnasAsync() {
            return base.Channel.getNoColumnasAsync();
        }
        
        public int getNoUnidades() {
            return base.Channel.getNoUnidades();
        }
        
        public System.Threading.Tasks.Task<int> getNoUnidadesAsync() {
            return base.Channel.getNoUnidadesAsync();
        }
        
        public int getNoJugador() {
            return base.Channel.getNoJugador();
        }
        
        public System.Threading.Tasks.Task<int> getNoJugadorAsync() {
            return base.Channel.getNoJugadorAsync();
        }
        
        public void setNoJugador(int jugador) {
            base.Channel.setNoJugador(jugador);
        }
        
        public System.Threading.Tasks.Task setNoJugadorAsync(int jugador) {
            return base.Channel.setNoJugadorAsync(jugador);
        }
        
        public bool insertarUnidad(AppCliente.NavalService.Unidad item, int fila, string columna) {
            return base.Channel.insertarUnidad(item, fila, columna);
        }
        
        public System.Threading.Tasks.Task<bool> insertarUnidadAsync(AppCliente.NavalService.Unidad item, int fila, string columna) {
            return base.Channel.insertarUnidadAsync(item, fila, columna);
        }
        
        public AppCliente.NavalService.Unidad newUnidad(string nombre, string x, int y, string duenyo, int vivo) {
            return base.Channel.newUnidad(nombre, x, y, duenyo, vivo);
        }
        
        public System.Threading.Tasks.Task<AppCliente.NavalService.Unidad> newUnidadAsync(string nombre, string x, int y, string duenyo, int vivo) {
            return base.Channel.newUnidadAsync(nombre, x, y, duenyo, vivo);
        }
        
        public bool graficarTablero(int nivel) {
            return base.Channel.graficarTablero(nivel);
        }
        
        public System.Threading.Tasks.Task<bool> graficarTableroAsync(int nivel) {
            return base.Channel.graficarTableroAsync(nivel);
        }
    }
}
