//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAdmin.NWwervice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodoOfPersona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NodoOfPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.NodoOfPersona izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.NodoOfPersona derField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.Persona ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        private int AlturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClienteAdmin.NWwervice.NodoOfPersona izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClienteAdmin.NWwervice.NodoOfPersona der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteAdmin.NWwervice.Persona Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Altura {
            get {
                return this.AlturaField;
            }
            set {
                if ((this.AlturaField.Equals(value) != true)) {
                    this.AlturaField = value;
                    this.RaisePropertyChanged("Altura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        private bool ConectadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Conectado {
            get {
                return this.ConectadoField;
            }
            set {
                if ((this.ConectadoField.Equals(value) != true)) {
                    this.ConectadoField = value;
                    this.RaisePropertyChanged("Conectado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NWwervice.NavalWarsWSSoap")]
    public interface NavalWarsWSSoap {
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioInsertar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioInsertarResponse binarioInsertar(ClienteAdmin.NWwervice.binarioInsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> binarioInsertarAsync(ClienteAdmin.NWwervice.binarioInsertarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioBuscar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioBuscarResponse binarioBuscar(ClienteAdmin.NWwervice.binarioBuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> binarioBuscarAsync(ClienteAdmin.NWwervice.binarioBuscarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioModificar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioModificarResponse binarioModificar(ClienteAdmin.NWwervice.binarioModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioModificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> binarioModificarAsync(ClienteAdmin.NWwervice.binarioModificarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioEliminar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioEliminarResponse binarioEliminar(ClienteAdmin.NWwervice.binarioEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> binarioEliminarAsync(ClienteAdmin.NWwervice.binarioEliminarRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaMasiva", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioCargaMasivaResponse binarioCargaMasiva(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaMasiva", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> binarioCargaMasivaAsync(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request);
        
        // CODEGEN: Generating message contract since element name listarUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarUsuarios", ReplyAction="*")]
        ClienteAdmin.NWwervice.listarUsuariosResponse listarUsuarios(ClienteAdmin.NWwervice.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> listarUsuariosAsync(ClienteAdmin.NWwervice.listarUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/avlInsertar", ReplyAction="*")]
        ClienteAdmin.NWwervice.avlInsertarResponse avlInsertar(ClienteAdmin.NWwervice.avlInsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/avlInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.avlInsertarResponse> avlInsertarAsync(ClienteAdmin.NWwervice.avlInsertarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioInsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioInsertar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioInsertarRequestBody Body;
        
        public binarioInsertarRequest() {
        }
        
        public binarioInsertarRequest(ClienteAdmin.NWwervice.binarioInsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioInsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public binarioInsertarRequestBody() {
        }
        
        public binarioInsertarRequestBody(string nick, string mail, string password) {
            this.nick = nick;
            this.mail = mail;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioInsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioInsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioInsertarResponseBody Body;
        
        public binarioInsertarResponse() {
        }
        
        public binarioInsertarResponse(ClienteAdmin.NWwervice.binarioInsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioInsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioInsertarResult;
        
        public binarioInsertarResponseBody() {
        }
        
        public binarioInsertarResponseBody(bool binarioInsertarResult) {
            this.binarioInsertarResult = binarioInsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioBuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioBuscar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioBuscarRequestBody Body;
        
        public binarioBuscarRequest() {
        }
        
        public binarioBuscarRequest(ClienteAdmin.NWwervice.binarioBuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioBuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        public binarioBuscarRequestBody() {
        }
        
        public binarioBuscarRequestBody(string nick) {
            this.nick = nick;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioBuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioBuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioBuscarResponseBody Body;
        
        public binarioBuscarResponse() {
        }
        
        public binarioBuscarResponse(ClienteAdmin.NWwervice.binarioBuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioBuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteAdmin.NWwervice.NodoOfPersona binarioBuscarResult;
        
        public binarioBuscarResponseBody() {
        }
        
        public binarioBuscarResponseBody(ClienteAdmin.NWwervice.NodoOfPersona binarioBuscarResult) {
            this.binarioBuscarResult = binarioBuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioModificar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioModificarRequestBody Body;
        
        public binarioModificarRequest() {
        }
        
        public binarioModificarRequest(ClienteAdmin.NWwervice.binarioModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool conectado;
        
        public binarioModificarRequestBody() {
        }
        
        public binarioModificarRequestBody(string nick, string mail, string password, bool conectado) {
            this.nick = nick;
            this.mail = mail;
            this.password = password;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioModificarResponseBody Body;
        
        public binarioModificarResponse() {
        }
        
        public binarioModificarResponse(ClienteAdmin.NWwervice.binarioModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioModificarResult;
        
        public binarioModificarResponseBody() {
        }
        
        public binarioModificarResponseBody(bool binarioModificarResult) {
            this.binarioModificarResult = binarioModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioEliminar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioEliminarRequestBody Body;
        
        public binarioEliminarRequest() {
        }
        
        public binarioEliminarRequest(ClienteAdmin.NWwervice.binarioEliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioEliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        public binarioEliminarRequestBody() {
        }
        
        public binarioEliminarRequestBody(string nick) {
            this.nick = nick;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioEliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioEliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioEliminarResponseBody Body;
        
        public binarioEliminarResponse() {
        }
        
        public binarioEliminarResponse(ClienteAdmin.NWwervice.binarioEliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioEliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioEliminarResult;
        
        public binarioEliminarResponseBody() {
        }
        
        public binarioEliminarResponseBody(bool binarioEliminarResult) {
            this.binarioEliminarResult = binarioEliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaMasivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaMasiva", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody Body;
        
        public binarioCargaMasivaRequest() {
        }
        
        public binarioCargaMasivaRequest(ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaMasivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public binarioCargaMasivaRequestBody() {
        }
        
        public binarioCargaMasivaRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaMasivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaMasivaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaMasivaResponseBody Body;
        
        public binarioCargaMasivaResponse() {
        }
        
        public binarioCargaMasivaResponse(ClienteAdmin.NWwervice.binarioCargaMasivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaMasivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioCargaMasivaResult;
        
        public binarioCargaMasivaResponseBody() {
        }
        
        public binarioCargaMasivaResponseBody(bool binarioCargaMasivaResult) {
            this.binarioCargaMasivaResult = binarioCargaMasivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.listarUsuariosRequestBody Body;
        
        public listarUsuariosRequest() {
        }
        
        public listarUsuariosRequest(ClienteAdmin.NWwervice.listarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarUsuariosRequestBody {
        
        public listarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.listarUsuariosResponseBody Body;
        
        public listarUsuariosResponse() {
        }
        
        public listarUsuariosResponse(ClienteAdmin.NWwervice.listarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarUsuariosResult;
        
        public listarUsuariosResponseBody() {
        }
        
        public listarUsuariosResponseBody(string listarUsuariosResult) {
            this.listarUsuariosResult = listarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class avlInsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="avlInsertar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.avlInsertarRequestBody Body;
        
        public avlInsertarRequest() {
        }
        
        public avlInsertarRequest(ClienteAdmin.NWwervice.avlInsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class avlInsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public avlInsertarRequestBody() {
        }
        
        public avlInsertarRequestBody(string nick, string mail, string password) {
            this.nick = nick;
            this.mail = mail;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class avlInsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="avlInsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.avlInsertarResponseBody Body;
        
        public avlInsertarResponse() {
        }
        
        public avlInsertarResponse(ClienteAdmin.NWwervice.avlInsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class avlInsertarResponseBody {
        
        public avlInsertarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NavalWarsWSSoapChannel : ClienteAdmin.NWwervice.NavalWarsWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NavalWarsWSSoapClient : System.ServiceModel.ClientBase<ClienteAdmin.NWwervice.NavalWarsWSSoap>, ClienteAdmin.NWwervice.NavalWarsWSSoap {
        
        public NavalWarsWSSoapClient() {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioInsertarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioInsertar(ClienteAdmin.NWwervice.binarioInsertarRequest request) {
            return base.Channel.binarioInsertar(request);
        }
        
        public bool binarioInsertar(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.binarioInsertarRequest inValue = new ClienteAdmin.NWwervice.binarioInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            ClienteAdmin.NWwervice.binarioInsertarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioInsertar(inValue);
            return retVal.Body.binarioInsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioInsertarAsync(ClienteAdmin.NWwervice.binarioInsertarRequest request) {
            return base.Channel.binarioInsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> binarioInsertarAsync(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.binarioInsertarRequest inValue = new ClienteAdmin.NWwervice.binarioInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioInsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioBuscarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioBuscar(ClienteAdmin.NWwervice.binarioBuscarRequest request) {
            return base.Channel.binarioBuscar(request);
        }
        
        public ClienteAdmin.NWwervice.NodoOfPersona binarioBuscar(string nick) {
            ClienteAdmin.NWwervice.binarioBuscarRequest inValue = new ClienteAdmin.NWwervice.binarioBuscarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioBuscarRequestBody();
            inValue.Body.nick = nick;
            ClienteAdmin.NWwervice.binarioBuscarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioBuscar(inValue);
            return retVal.Body.binarioBuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioBuscarAsync(ClienteAdmin.NWwervice.binarioBuscarRequest request) {
            return base.Channel.binarioBuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> binarioBuscarAsync(string nick) {
            ClienteAdmin.NWwervice.binarioBuscarRequest inValue = new ClienteAdmin.NWwervice.binarioBuscarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioBuscarRequestBody();
            inValue.Body.nick = nick;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioBuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioModificarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioModificar(ClienteAdmin.NWwervice.binarioModificarRequest request) {
            return base.Channel.binarioModificar(request);
        }
        
        public bool binarioModificar(string nick, string mail, string password, bool conectado) {
            ClienteAdmin.NWwervice.binarioModificarRequest inValue = new ClienteAdmin.NWwervice.binarioModificarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioModificarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            inValue.Body.conectado = conectado;
            ClienteAdmin.NWwervice.binarioModificarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioModificar(inValue);
            return retVal.Body.binarioModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioModificarAsync(ClienteAdmin.NWwervice.binarioModificarRequest request) {
            return base.Channel.binarioModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> binarioModificarAsync(string nick, string mail, string password, bool conectado) {
            ClienteAdmin.NWwervice.binarioModificarRequest inValue = new ClienteAdmin.NWwervice.binarioModificarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioModificarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            inValue.Body.conectado = conectado;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioEliminarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioEliminar(ClienteAdmin.NWwervice.binarioEliminarRequest request) {
            return base.Channel.binarioEliminar(request);
        }
        
        public bool binarioEliminar(string nick) {
            ClienteAdmin.NWwervice.binarioEliminarRequest inValue = new ClienteAdmin.NWwervice.binarioEliminarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioEliminarRequestBody();
            inValue.Body.nick = nick;
            ClienteAdmin.NWwervice.binarioEliminarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioEliminar(inValue);
            return retVal.Body.binarioEliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioEliminarAsync(ClienteAdmin.NWwervice.binarioEliminarRequest request) {
            return base.Channel.binarioEliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> binarioEliminarAsync(string nick) {
            ClienteAdmin.NWwervice.binarioEliminarRequest inValue = new ClienteAdmin.NWwervice.binarioEliminarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioEliminarRequestBody();
            inValue.Body.nick = nick;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioEliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioCargaMasivaResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaMasiva(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request) {
            return base.Channel.binarioCargaMasiva(request);
        }
        
        public bool binarioCargaMasiva(string url) {
            ClienteAdmin.NWwervice.binarioCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.binarioCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody();
            inValue.Body.url = url;
            ClienteAdmin.NWwervice.binarioCargaMasivaResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaMasiva(inValue);
            return retVal.Body.binarioCargaMasivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaMasivaAsync(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request) {
            return base.Channel.binarioCargaMasivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> binarioCargaMasivaAsync(string url) {
            ClienteAdmin.NWwervice.binarioCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.binarioCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody();
            inValue.Body.url = url;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaMasivaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.listarUsuariosResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.listarUsuarios(ClienteAdmin.NWwervice.listarUsuariosRequest request) {
            return base.Channel.listarUsuarios(request);
        }
        
        public string listarUsuarios() {
            ClienteAdmin.NWwervice.listarUsuariosRequest inValue = new ClienteAdmin.NWwervice.listarUsuariosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.listarUsuariosRequestBody();
            ClienteAdmin.NWwervice.listarUsuariosResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).listarUsuarios(inValue);
            return retVal.Body.listarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.listarUsuariosAsync(ClienteAdmin.NWwervice.listarUsuariosRequest request) {
            return base.Channel.listarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> listarUsuariosAsync() {
            ClienteAdmin.NWwervice.listarUsuariosRequest inValue = new ClienteAdmin.NWwervice.listarUsuariosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.listarUsuariosRequestBody();
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).listarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.avlInsertarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.avlInsertar(ClienteAdmin.NWwervice.avlInsertarRequest request) {
            return base.Channel.avlInsertar(request);
        }
        
        public void avlInsertar(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.avlInsertarRequest inValue = new ClienteAdmin.NWwervice.avlInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.avlInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            ClienteAdmin.NWwervice.avlInsertarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).avlInsertar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.avlInsertarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.avlInsertarAsync(ClienteAdmin.NWwervice.avlInsertarRequest request) {
            return base.Channel.avlInsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.avlInsertarResponse> avlInsertarAsync(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.avlInsertarRequest inValue = new ClienteAdmin.NWwervice.avlInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.avlInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).avlInsertarAsync(inValue);
        }
    }
}
