//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAdmin.NWwervice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.ListaDOfJuego juegosField;
        
        private bool ConectadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteAdmin.NWwervice.ListaDOfJuego juegos {
            get {
                return this.juegosField;
            }
            set {
                if ((object.ReferenceEquals(this.juegosField, value) != true)) {
                    this.juegosField = value;
                    this.RaisePropertyChanged("juegos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Conectado {
            get {
                return this.ConectadoField;
            }
            set {
                if ((this.ConectadoField.Equals(value) != true)) {
                    this.ConectadoField = value;
                    this.RaisePropertyChanged("Conectado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDOfJuego", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaDOfJuego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.NodoDOfJuego raizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.NodoDOfJuego finField;
        
        private int countField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClienteAdmin.NWwervice.NodoDOfJuego raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClienteAdmin.NWwervice.NodoDOfJuego fin {
            get {
                return this.finField;
            }
            set {
                if ((object.ReferenceEquals(this.finField, value) != true)) {
                    this.finField = value;
                    this.RaisePropertyChanged("fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodoDOfJuego", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NodoDOfJuego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.NodoDOfJuego siguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteAdmin.NWwervice.Juego ItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClienteAdmin.NWwervice.NodoDOfJuego siguiente {
            get {
                return this.siguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.siguienteField, value) != true)) {
                    this.siguienteField = value;
                    this.RaisePropertyChanged("siguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClienteAdmin.NWwervice.Juego Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Juego", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Juego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OponenteField;
        
        private int Unidades_desplegadasField;
        
        private int Unidades_sobrevivientesField;
        
        private int Unidades_destruidas_por_miField;
        
        private bool GaneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Oponente {
            get {
                return this.OponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.OponenteField, value) != true)) {
                    this.OponenteField = value;
                    this.RaisePropertyChanged("Oponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Unidades_desplegadas {
            get {
                return this.Unidades_desplegadasField;
            }
            set {
                if ((this.Unidades_desplegadasField.Equals(value) != true)) {
                    this.Unidades_desplegadasField = value;
                    this.RaisePropertyChanged("Unidades_desplegadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Unidades_sobrevivientes {
            get {
                return this.Unidades_sobrevivientesField;
            }
            set {
                if ((this.Unidades_sobrevivientesField.Equals(value) != true)) {
                    this.Unidades_sobrevivientesField = value;
                    this.RaisePropertyChanged("Unidades_sobrevivientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Unidades_destruidas_por_mi {
            get {
                return this.Unidades_destruidas_por_miField;
            }
            set {
                if ((this.Unidades_destruidas_por_miField.Equals(value) != true)) {
                    this.Unidades_destruidas_por_miField = value;
                    this.RaisePropertyChanged("Unidades_destruidas_por_mi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Gane {
            get {
                return this.GaneField;
            }
            set {
                if ((this.GaneField.Equals(value) != true)) {
                    this.GaneField = value;
                    this.RaisePropertyChanged("Gane");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NWwervice.NavalWarsWSSoap")]
    public interface NavalWarsWSSoap {
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioInsertar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioInsertarResponse binarioInsertar(ClienteAdmin.NWwervice.binarioInsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> binarioInsertarAsync(ClienteAdmin.NWwervice.binarioInsertarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioBuscar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioBuscarResponse binarioBuscar(ClienteAdmin.NWwervice.binarioBuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> binarioBuscarAsync(ClienteAdmin.NWwervice.binarioBuscarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioModificar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioModificarResponse binarioModificar(ClienteAdmin.NWwervice.binarioModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioModificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> binarioModificarAsync(ClienteAdmin.NWwervice.binarioModificarRequest request);
        
        // CODEGEN: Generating message contract since element name nick from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioEliminar", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioEliminarResponse binarioEliminar(ClienteAdmin.NWwervice.binarioEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> binarioEliminarAsync(ClienteAdmin.NWwervice.binarioEliminarRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaMasiva", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioCargaMasivaResponse binarioCargaMasiva(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaMasiva", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> binarioCargaMasivaAsync(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaJuegos", ReplyAction="*")]
        ClienteAdmin.NWwervice.binarioCargaJuegosResponse binarioCargaJuegos(ClienteAdmin.NWwervice.binarioCargaJuegosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binarioCargaJuegos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaJuegosResponse> binarioCargaJuegosAsync(ClienteAdmin.NWwervice.binarioCargaJuegosRequest request);
        
        // CODEGEN: Generating message contract since element name listarUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarUsuarios", ReplyAction="*")]
        ClienteAdmin.NWwervice.listarUsuariosResponse listarUsuarios(ClienteAdmin.NWwervice.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> listarUsuariosAsync(ClienteAdmin.NWwervice.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bSetGrado", ReplyAction="*")]
        void bSetGrado(int grado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bSetGrado", ReplyAction="*")]
        System.Threading.Tasks.Task bSetGradoAsync(int grado);
        
        // CODEGEN: Generating message contract since element name patron from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bSetPatron", ReplyAction="*")]
        ClienteAdmin.NWwervice.bSetPatronResponse bSetPatron(ClienteAdmin.NWwervice.bSetPatronRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bSetPatron", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bSetPatronResponse> bSetPatronAsync(ClienteAdmin.NWwervice.bSetPatronRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bCargaMasiva", ReplyAction="*")]
        ClienteAdmin.NWwervice.bCargaMasivaResponse bCargaMasiva(ClienteAdmin.NWwervice.bCargaMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bCargaMasiva", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bCargaMasivaResponse> bCargaMasivaAsync(ClienteAdmin.NWwervice.bCargaMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debugJuego", ReplyAction="*")]
        void debugJuego();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debugJuego", ReplyAction="*")]
        System.Threading.Tasks.Task debugJuegoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debugMord", ReplyAction="*")]
        int debugMord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debugMord", ReplyAction="*")]
        System.Threading.Tasks.Task<int> debugMordAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioInsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioInsertar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioInsertarRequestBody Body;
        
        public binarioInsertarRequest() {
        }
        
        public binarioInsertarRequest(ClienteAdmin.NWwervice.binarioInsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioInsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public binarioInsertarRequestBody() {
        }
        
        public binarioInsertarRequestBody(string nick, string mail, string password) {
            this.nick = nick;
            this.mail = mail;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioInsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioInsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioInsertarResponseBody Body;
        
        public binarioInsertarResponse() {
        }
        
        public binarioInsertarResponse(ClienteAdmin.NWwervice.binarioInsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioInsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioInsertarResult;
        
        public binarioInsertarResponseBody() {
        }
        
        public binarioInsertarResponseBody(bool binarioInsertarResult) {
            this.binarioInsertarResult = binarioInsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioBuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioBuscar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioBuscarRequestBody Body;
        
        public binarioBuscarRequest() {
        }
        
        public binarioBuscarRequest(ClienteAdmin.NWwervice.binarioBuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioBuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        public binarioBuscarRequestBody() {
        }
        
        public binarioBuscarRequestBody(string nick) {
            this.nick = nick;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioBuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioBuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioBuscarResponseBody Body;
        
        public binarioBuscarResponse() {
        }
        
        public binarioBuscarResponse(ClienteAdmin.NWwervice.binarioBuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioBuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteAdmin.NWwervice.Persona binarioBuscarResult;
        
        public binarioBuscarResponseBody() {
        }
        
        public binarioBuscarResponseBody(ClienteAdmin.NWwervice.Persona binarioBuscarResult) {
            this.binarioBuscarResult = binarioBuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioModificar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioModificarRequestBody Body;
        
        public binarioModificarRequest() {
        }
        
        public binarioModificarRequest(ClienteAdmin.NWwervice.binarioModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool conectado;
        
        public binarioModificarRequestBody() {
        }
        
        public binarioModificarRequestBody(string nick, string mail, string password, bool conectado) {
            this.nick = nick;
            this.mail = mail;
            this.password = password;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioModificarResponseBody Body;
        
        public binarioModificarResponse() {
        }
        
        public binarioModificarResponse(ClienteAdmin.NWwervice.binarioModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioModificarResult;
        
        public binarioModificarResponseBody() {
        }
        
        public binarioModificarResponseBody(bool binarioModificarResult) {
            this.binarioModificarResult = binarioModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioEliminar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioEliminarRequestBody Body;
        
        public binarioEliminarRequest() {
        }
        
        public binarioEliminarRequest(ClienteAdmin.NWwervice.binarioEliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioEliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        public binarioEliminarRequestBody() {
        }
        
        public binarioEliminarRequestBody(string nick) {
            this.nick = nick;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioEliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioEliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioEliminarResponseBody Body;
        
        public binarioEliminarResponse() {
        }
        
        public binarioEliminarResponse(ClienteAdmin.NWwervice.binarioEliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioEliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioEliminarResult;
        
        public binarioEliminarResponseBody() {
        }
        
        public binarioEliminarResponseBody(bool binarioEliminarResult) {
            this.binarioEliminarResult = binarioEliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaMasivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaMasiva", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody Body;
        
        public binarioCargaMasivaRequest() {
        }
        
        public binarioCargaMasivaRequest(ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaMasivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public binarioCargaMasivaRequestBody() {
        }
        
        public binarioCargaMasivaRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaMasivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaMasivaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaMasivaResponseBody Body;
        
        public binarioCargaMasivaResponse() {
        }
        
        public binarioCargaMasivaResponse(ClienteAdmin.NWwervice.binarioCargaMasivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaMasivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioCargaMasivaResult;
        
        public binarioCargaMasivaResponseBody() {
        }
        
        public binarioCargaMasivaResponseBody(bool binarioCargaMasivaResult) {
            this.binarioCargaMasivaResult = binarioCargaMasivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaJuegosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaJuegos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaJuegosRequestBody Body;
        
        public binarioCargaJuegosRequest() {
        }
        
        public binarioCargaJuegosRequest(ClienteAdmin.NWwervice.binarioCargaJuegosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaJuegosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public binarioCargaJuegosRequestBody() {
        }
        
        public binarioCargaJuegosRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binarioCargaJuegosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binarioCargaJuegosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.binarioCargaJuegosResponseBody Body;
        
        public binarioCargaJuegosResponse() {
        }
        
        public binarioCargaJuegosResponse(ClienteAdmin.NWwervice.binarioCargaJuegosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binarioCargaJuegosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool binarioCargaJuegosResult;
        
        public binarioCargaJuegosResponseBody() {
        }
        
        public binarioCargaJuegosResponseBody(bool binarioCargaJuegosResult) {
            this.binarioCargaJuegosResult = binarioCargaJuegosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.listarUsuariosRequestBody Body;
        
        public listarUsuariosRequest() {
        }
        
        public listarUsuariosRequest(ClienteAdmin.NWwervice.listarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarUsuariosRequestBody {
        
        public listarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.listarUsuariosResponseBody Body;
        
        public listarUsuariosResponse() {
        }
        
        public listarUsuariosResponse(ClienteAdmin.NWwervice.listarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarUsuariosResult;
        
        public listarUsuariosResponseBody() {
        }
        
        public listarUsuariosResponseBody(string listarUsuariosResult) {
            this.listarUsuariosResult = listarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bSetPatronRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bSetPatron", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.bSetPatronRequestBody Body;
        
        public bSetPatronRequest() {
        }
        
        public bSetPatronRequest(ClienteAdmin.NWwervice.bSetPatronRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bSetPatronRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string patron;
        
        public bSetPatronRequestBody() {
        }
        
        public bSetPatronRequestBody(string patron) {
            this.patron = patron;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bSetPatronResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bSetPatronResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.bSetPatronResponseBody Body;
        
        public bSetPatronResponse() {
        }
        
        public bSetPatronResponse(ClienteAdmin.NWwervice.bSetPatronResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class bSetPatronResponseBody {
        
        public bSetPatronResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bCargaMasivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bCargaMasiva", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.bCargaMasivaRequestBody Body;
        
        public bCargaMasivaRequest() {
        }
        
        public bCargaMasivaRequest(ClienteAdmin.NWwervice.bCargaMasivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bCargaMasivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public bCargaMasivaRequestBody() {
        }
        
        public bCargaMasivaRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bCargaMasivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bCargaMasivaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAdmin.NWwervice.bCargaMasivaResponseBody Body;
        
        public bCargaMasivaResponse() {
        }
        
        public bCargaMasivaResponse(ClienteAdmin.NWwervice.bCargaMasivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bCargaMasivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool bCargaMasivaResult;
        
        public bCargaMasivaResponseBody() {
        }
        
        public bCargaMasivaResponseBody(bool bCargaMasivaResult) {
            this.bCargaMasivaResult = bCargaMasivaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NavalWarsWSSoapChannel : ClienteAdmin.NWwervice.NavalWarsWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NavalWarsWSSoapClient : System.ServiceModel.ClientBase<ClienteAdmin.NWwervice.NavalWarsWSSoap>, ClienteAdmin.NWwervice.NavalWarsWSSoap {
        
        public NavalWarsWSSoapClient() {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NavalWarsWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioInsertarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioInsertar(ClienteAdmin.NWwervice.binarioInsertarRequest request) {
            return base.Channel.binarioInsertar(request);
        }
        
        public bool binarioInsertar(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.binarioInsertarRequest inValue = new ClienteAdmin.NWwervice.binarioInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            ClienteAdmin.NWwervice.binarioInsertarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioInsertar(inValue);
            return retVal.Body.binarioInsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioInsertarAsync(ClienteAdmin.NWwervice.binarioInsertarRequest request) {
            return base.Channel.binarioInsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioInsertarResponse> binarioInsertarAsync(string nick, string mail, string password) {
            ClienteAdmin.NWwervice.binarioInsertarRequest inValue = new ClienteAdmin.NWwervice.binarioInsertarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioInsertarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioInsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioBuscarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioBuscar(ClienteAdmin.NWwervice.binarioBuscarRequest request) {
            return base.Channel.binarioBuscar(request);
        }
        
        public ClienteAdmin.NWwervice.Persona binarioBuscar(string nick) {
            ClienteAdmin.NWwervice.binarioBuscarRequest inValue = new ClienteAdmin.NWwervice.binarioBuscarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioBuscarRequestBody();
            inValue.Body.nick = nick;
            ClienteAdmin.NWwervice.binarioBuscarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioBuscar(inValue);
            return retVal.Body.binarioBuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioBuscarAsync(ClienteAdmin.NWwervice.binarioBuscarRequest request) {
            return base.Channel.binarioBuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioBuscarResponse> binarioBuscarAsync(string nick) {
            ClienteAdmin.NWwervice.binarioBuscarRequest inValue = new ClienteAdmin.NWwervice.binarioBuscarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioBuscarRequestBody();
            inValue.Body.nick = nick;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioBuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioModificarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioModificar(ClienteAdmin.NWwervice.binarioModificarRequest request) {
            return base.Channel.binarioModificar(request);
        }
        
        public bool binarioModificar(string nick, string mail, string password, bool conectado) {
            ClienteAdmin.NWwervice.binarioModificarRequest inValue = new ClienteAdmin.NWwervice.binarioModificarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioModificarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            inValue.Body.conectado = conectado;
            ClienteAdmin.NWwervice.binarioModificarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioModificar(inValue);
            return retVal.Body.binarioModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioModificarAsync(ClienteAdmin.NWwervice.binarioModificarRequest request) {
            return base.Channel.binarioModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioModificarResponse> binarioModificarAsync(string nick, string mail, string password, bool conectado) {
            ClienteAdmin.NWwervice.binarioModificarRequest inValue = new ClienteAdmin.NWwervice.binarioModificarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioModificarRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.mail = mail;
            inValue.Body.password = password;
            inValue.Body.conectado = conectado;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioEliminarResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioEliminar(ClienteAdmin.NWwervice.binarioEliminarRequest request) {
            return base.Channel.binarioEliminar(request);
        }
        
        public bool binarioEliminar(string nick) {
            ClienteAdmin.NWwervice.binarioEliminarRequest inValue = new ClienteAdmin.NWwervice.binarioEliminarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioEliminarRequestBody();
            inValue.Body.nick = nick;
            ClienteAdmin.NWwervice.binarioEliminarResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioEliminar(inValue);
            return retVal.Body.binarioEliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioEliminarAsync(ClienteAdmin.NWwervice.binarioEliminarRequest request) {
            return base.Channel.binarioEliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioEliminarResponse> binarioEliminarAsync(string nick) {
            ClienteAdmin.NWwervice.binarioEliminarRequest inValue = new ClienteAdmin.NWwervice.binarioEliminarRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioEliminarRequestBody();
            inValue.Body.nick = nick;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioEliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioCargaMasivaResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaMasiva(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request) {
            return base.Channel.binarioCargaMasiva(request);
        }
        
        public bool binarioCargaMasiva(string url) {
            ClienteAdmin.NWwervice.binarioCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.binarioCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody();
            inValue.Body.url = url;
            ClienteAdmin.NWwervice.binarioCargaMasivaResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaMasiva(inValue);
            return retVal.Body.binarioCargaMasivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaMasivaAsync(ClienteAdmin.NWwervice.binarioCargaMasivaRequest request) {
            return base.Channel.binarioCargaMasivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaMasivaResponse> binarioCargaMasivaAsync(string url) {
            ClienteAdmin.NWwervice.binarioCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.binarioCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaMasivaRequestBody();
            inValue.Body.url = url;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaMasivaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.binarioCargaJuegosResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaJuegos(ClienteAdmin.NWwervice.binarioCargaJuegosRequest request) {
            return base.Channel.binarioCargaJuegos(request);
        }
        
        public bool binarioCargaJuegos(string url) {
            ClienteAdmin.NWwervice.binarioCargaJuegosRequest inValue = new ClienteAdmin.NWwervice.binarioCargaJuegosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaJuegosRequestBody();
            inValue.Body.url = url;
            ClienteAdmin.NWwervice.binarioCargaJuegosResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaJuegos(inValue);
            return retVal.Body.binarioCargaJuegosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaJuegosResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.binarioCargaJuegosAsync(ClienteAdmin.NWwervice.binarioCargaJuegosRequest request) {
            return base.Channel.binarioCargaJuegosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.binarioCargaJuegosResponse> binarioCargaJuegosAsync(string url) {
            ClienteAdmin.NWwervice.binarioCargaJuegosRequest inValue = new ClienteAdmin.NWwervice.binarioCargaJuegosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.binarioCargaJuegosRequestBody();
            inValue.Body.url = url;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).binarioCargaJuegosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.listarUsuariosResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.listarUsuarios(ClienteAdmin.NWwervice.listarUsuariosRequest request) {
            return base.Channel.listarUsuarios(request);
        }
        
        public string listarUsuarios() {
            ClienteAdmin.NWwervice.listarUsuariosRequest inValue = new ClienteAdmin.NWwervice.listarUsuariosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.listarUsuariosRequestBody();
            ClienteAdmin.NWwervice.listarUsuariosResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).listarUsuarios(inValue);
            return retVal.Body.listarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.listarUsuariosAsync(ClienteAdmin.NWwervice.listarUsuariosRequest request) {
            return base.Channel.listarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.listarUsuariosResponse> listarUsuariosAsync() {
            ClienteAdmin.NWwervice.listarUsuariosRequest inValue = new ClienteAdmin.NWwervice.listarUsuariosRequest();
            inValue.Body = new ClienteAdmin.NWwervice.listarUsuariosRequestBody();
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).listarUsuariosAsync(inValue);
        }
        
        public void bSetGrado(int grado) {
            base.Channel.bSetGrado(grado);
        }
        
        public System.Threading.Tasks.Task bSetGradoAsync(int grado) {
            return base.Channel.bSetGradoAsync(grado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.bSetPatronResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.bSetPatron(ClienteAdmin.NWwervice.bSetPatronRequest request) {
            return base.Channel.bSetPatron(request);
        }
        
        public void bSetPatron(string patron) {
            ClienteAdmin.NWwervice.bSetPatronRequest inValue = new ClienteAdmin.NWwervice.bSetPatronRequest();
            inValue.Body = new ClienteAdmin.NWwervice.bSetPatronRequestBody();
            inValue.Body.patron = patron;
            ClienteAdmin.NWwervice.bSetPatronResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).bSetPatron(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bSetPatronResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.bSetPatronAsync(ClienteAdmin.NWwervice.bSetPatronRequest request) {
            return base.Channel.bSetPatronAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bSetPatronResponse> bSetPatronAsync(string patron) {
            ClienteAdmin.NWwervice.bSetPatronRequest inValue = new ClienteAdmin.NWwervice.bSetPatronRequest();
            inValue.Body = new ClienteAdmin.NWwervice.bSetPatronRequestBody();
            inValue.Body.patron = patron;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).bSetPatronAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAdmin.NWwervice.bCargaMasivaResponse ClienteAdmin.NWwervice.NavalWarsWSSoap.bCargaMasiva(ClienteAdmin.NWwervice.bCargaMasivaRequest request) {
            return base.Channel.bCargaMasiva(request);
        }
        
        public bool bCargaMasiva(string url) {
            ClienteAdmin.NWwervice.bCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.bCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.bCargaMasivaRequestBody();
            inValue.Body.url = url;
            ClienteAdmin.NWwervice.bCargaMasivaResponse retVal = ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).bCargaMasiva(inValue);
            return retVal.Body.bCargaMasivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bCargaMasivaResponse> ClienteAdmin.NWwervice.NavalWarsWSSoap.bCargaMasivaAsync(ClienteAdmin.NWwervice.bCargaMasivaRequest request) {
            return base.Channel.bCargaMasivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAdmin.NWwervice.bCargaMasivaResponse> bCargaMasivaAsync(string url) {
            ClienteAdmin.NWwervice.bCargaMasivaRequest inValue = new ClienteAdmin.NWwervice.bCargaMasivaRequest();
            inValue.Body = new ClienteAdmin.NWwervice.bCargaMasivaRequestBody();
            inValue.Body.url = url;
            return ((ClienteAdmin.NWwervice.NavalWarsWSSoap)(this)).bCargaMasivaAsync(inValue);
        }
        
        public void debugJuego() {
            base.Channel.debugJuego();
        }
        
        public System.Threading.Tasks.Task debugJuegoAsync() {
            return base.Channel.debugJuegoAsync();
        }
        
        public int debugMord() {
            return base.Channel.debugMord();
        }
        
        public System.Threading.Tasks.Task<int> debugMordAsync() {
            return base.Channel.debugMordAsync();
        }
    }
}
