//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.TestService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int edadField;
        
        private string mailField;
        
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.IServiceClasses")]
    public interface IServiceClasses {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClasses/getPersona", ReplyAction="http://tempuri.org/IServiceClasses/getPersonaResponse")]
        TestWeb.TestService.Persona getPersona(string nombre, int edad, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClasses/getPersona", ReplyAction="http://tempuri.org/IServiceClasses/getPersonaResponse")]
        System.Threading.Tasks.Task<TestWeb.TestService.Persona> getPersonaAsync(string nombre, int edad, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClasses/getFactorial", ReplyAction="http://tempuri.org/IServiceClasses/getFactorialResponse")]
        int getFactorial(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClasses/getFactorial", ReplyAction="http://tempuri.org/IServiceClasses/getFactorialResponse")]
        System.Threading.Tasks.Task<int> getFactorialAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClassesChannel : TestWeb.TestService.IServiceClasses, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClassesClient : System.ServiceModel.ClientBase<TestWeb.TestService.IServiceClasses>, TestWeb.TestService.IServiceClasses {
        
        public ServiceClassesClient() {
        }
        
        public ServiceClassesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClassesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClassesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClassesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb.TestService.Persona getPersona(string nombre, int edad, string mail) {
            return base.Channel.getPersona(nombre, edad, mail);
        }
        
        public System.Threading.Tasks.Task<TestWeb.TestService.Persona> getPersonaAsync(string nombre, int edad, string mail) {
            return base.Channel.getPersonaAsync(nombre, edad, mail);
        }
        
        public int getFactorial(int numero) {
            return base.Channel.getFactorial(numero);
        }
        
        public System.Threading.Tasks.Task<int> getFactorialAsync(int numero) {
            return base.Channel.getFactorialAsync(numero);
        }
    }
}
